### ISSUE TITLE
Add additional aspect ratios & resolutions

### ISSUE THREAD

**Issue by RobDavenport** [gamercade-io/gamercade_console#102]
I think it would be benefecial to explore a bigger variety of aspect ratios.

Currently, the console is using a 16:9 aspect ratio, but it could be benefecial to also support others such as 4:3, 1:1, or other common sizes, such as tall or portrait style ones.

This can be done a few different ways:
1. modifying the `Resolution` enum to be a struct, and hold both a size (ultralow, medium, high, etc) and an aspect ratio (wide, square, standard etc).
2. Just additing/appending more supported resolutions, like `LowSquare` or `HighWide`
3. Opening it up to be completely custom, and have recommended resolutions via the GUI.
4. Something completely different with an extended preset list of resolutions.

It's important to choose resolutions which scale up to pixel perfect sizes, or can display cleanly on 16:9 displays though, as this is currently the target platforms.

This would likely break older versions, but I think it's worth getting this done now as opposed to later.

**Comment by RobDavenport** [comment]
Some additional thoughts on this topic: The current resolutions were picked due to their ability to scale perfectly into either 1080p , 720p, or both. 

The currently supported resolutions are:
    - UltraLow, 128 x 72, 1080p 15x, 720p 10x
    - VeryLow, 160 x 90, 1080p 12x, 720p 8x
    - Low, 320 x 180, 1080p 6x, 720p 4x
    - Medium,  480 x 270, 1080p 4x, 720p not divisible
    - High, 640 x 360, 1080p 3x, 720p 2x
    - VeryHigh, 1280 x 720, 1080p not divisible, 720p 1x
    - UltraHigh, 1920 x 1080, 1080p 1x, 720p not divisible
    
So with that in mind, we should target these resolutions for UltraHigh and VeryHigh respectively:
1440 x 1080 and 960 x 720 for 4:3 ratio
1080 x 1080 and 720 x 720 for 1:1 ratio.

**Comment by erlend-sh** [comment]
> Alternatively, we could just open up the resolutions and allow them to be input by the user

I think a stricter selection is better. An oft-cited benefit of developing for a virtual console is that it is helpfully constrained.

You may even consider determining a *[default](https://blog.codinghorror.com/the-power-of-defaults/)* resolution that’s already set for people who just wanna get going as quickly as possible. I reckon that ought to be either the Low or High resolution; can only be one though!

**Comment by RobDavenport** [comment]
The default resolution is currently the `Low, 320x180` resolution @ 16:9 aspect ratio.

> I think a stricter selection is better. An oft-cited benefit of developing for a virtual console is that it is helpfully constrained.

Yep exactly the reason for opening this up to discussion. Flexibility is good, but too much could let people shoot themselves in the foot and end up with huge black bars or bad scaling.. Consistency is good, but too much and everything is the same.

But I do think it would be great to add in some square resolutions, like 
| Name      | Width | Height | Total Pixels |
|-----------|-------|--------|--------------|
| UltraLow  | 64    | 64     | 4,096        |
| VeryLow   | 128   | 128    | 16,384       |
| Low       | 256   | 256    | 65,536       |
| Medium    | 512   | 512    | 262,144      |
| High      | 720   | 720    | 518,400      |
| VeryHigh  | 1024  | 1024   | 1,048,576    |
| UltraHigh | 1080  | 1080   | 1,166,400    |

And potentially some 4:3 ones... but there are ~17 decent ones we could use which provide good scaling and flexibility back towards 1920x1080 target.

An example would be like 320x240, 640x480, 800x600, 1024x768 etc. Some iconic retro resolutions but don't really scale nicely into the 1920x1080 target.

**Comment by RobDavenport** [comment]
Closing this as it will be resolved in #98
